/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proiect_ISI;

public class App
{

    public String getGreeting()
    {
        return "Hello World!";
    }
    static Database bazadedate;

    public static void main(String[] args)
    {
        bazadedate = new Database();
        TomcatCustomServer server = new TomcatCustomServer();
        server.start();
    }

    public static Database getDatabase()
    {
        return bazadedate;
    }
}
